### ISSUE TITLE
Support `HEAD` requests

### ISSUE THREAD

**Issue by josephmturner** [alphapapa/plz.el#15]
Hello!

`curl` accomplishes `HEAD` requests with the `--head` flag. Would you be willing to add support for `HEAD` requests like `(plz 'head ...)`?

**Comment by alphapapa** [comment]
Hi Joseph,

Yes, of course, HEAD requests should be supported; they simply haven't been needed yet.  Thanks.

**Comment by josephmturner** [comment]
Great! Thank you!!

**Comment by alphapapa** [comment]
@josephmturner This should be working now.  To simply send a HEAD request (e.g. to verify that the server doesn't give an error code for a URL), do, e.g. `(plz 'head URL)`.  To examine the headers, use, e.g. `(plz-response-headers (plz 'head URL :as 'response))`.

BTW, I added a note crediting USHIN for sponsoring work on this feature.  Please let me know if it looks ok.

Thanks.

**Comment by josephmturner** [comment]
@alphapapa It works great! Thank you!
