### ISSUE TITLE
Do not signal error on successful non-`200` HTTP status codes

### ISSUE THREAD

**Issue by josephmturner** [alphapapa/plz.el#17]
Currently, `plz.el` signals `plz-http-error` on anything besides a status 200 code. According to [Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status), only status codes between 400-599 are errors.

I was confused when I received a successful [201 status code](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201) and `plz.el` signaled an HTTP error.

**Comment by alphapapa** [comment]
Hi Joseph,

Yes, this is an artifact of `plz` being relatively new and not having needed to interact with other 2xx codes before.  Issue #7 is also related to this.

The question now is how to handle other 2xx codes.  I guess we could simply treat them the same as 200, and clients that need to handle specific 2xx codes differently could use `:as 'response` and check the code in the `:then` function.

What do you think?  Thanks.

**Comment by Dima-369** [comment]
> The question now is how to handle other 2xx codes. I guess we could simply treat them the same as 200, and clients that need to handle specific 2xx codes differently could use :as 'response and check the code in the :then function.

That sounds great! I vote for this :)

Once this is implemented, it would be great if this is noted in the README with an example of how to check for the status code!

**Comment by josephmturner** [comment]
> The question now is how to handle other 2xx codes. I guess we could simply treat them the same as 200, and clients that need to handle specific 2xx codes differently could use `:as 'response` and check the code in the `:then` function.

I like this simple solution. If at some point it seems appropriate for `plz.el` to handle specific 2xx codes, that can be implemented later.

**Comment by josephmturner** [comment]
Thank you!

**Comment by alphapapa** [comment]
Going to reopen this to remind me to update the docs as [mentioned](https://github.com/alphapapa/plz.el/issues/17#issuecomment-1398322827).

**Comment by alphapapa** [comment]
Done.
