### ISSUE TITLE
Just return headers from `HEAD` requests

### ISSUE THREAD

**Issue by josephmturner** [alphapapa/plz.el#20]
Are there any downsides to simplifying `(plz-response-headers (plz 'head url :as 'response))` to `(plz 'head url)`?

**Comment by alphapapa** [comment]
Seems like a good idea.  :)  Thanks.  (Sorry I overlooked this issue for so long.)

**Comment by josephmturner** [comment]
Closed in favor of #35

**Comment by alphapapa** [comment]
Yeah, part of me still wants to consider doing this in the future, but it's probably better not to.
