### ISSUE TITLE
Using plz on Windows

### ISSUE THREAD

**Issue by kaibagley** [alphapapa/plz.el#31]
Emacs version: `GNU Emacs 28.2 (build 2, x86_64-w64-mingw32) of 2022-09-13`
`plz` version: 0.5.4
curl version (from curl.se): curl 8.1.2 (x86_64-w64-mingw32)

Using `plz` and/or `ement` on Windows throws errors:
When running either ement-connect or (plz 'get "https://httpbin.org/user-agent") I get the error:
error in process sentinel: plz: Curl error: "plz--sentinel: Curl error", #s(plz-error (2 . "Failed to initialize.") nil nil)

This is probably thanks to `curl` on Windows/PowerShell being an alias for `Invoke-WebRequest`

I understand that there is a variable within `plz`, called `plz-curl-program`, however changing this variable from "curl", to "curl.exe" (the Windows version of actual `curl` returns the same issues as above.

In another issue https://github.com/alphapapa/ement.el/issues/38, in an off-topic comment a user was able to change their default windows curl alias to be that of actual curl from [curl.se](https://curl.se/windows/), however even when adding this to my PATH, Powershell is unable to see the executable, and emacs certainly can't either.

The user also implied that they were able to change `plz-curl-program` to some other variable that enabled `plz` to use the correct `curl.exe`, but I am unable to figure out what to change this to.

**Comment by alphapapa** [comment]
PowerShell shouldn't be relevant here, because `plz` uses `make-process` not `shell-command`, so `curl` should be invoked directly, not through a shell.

As mentioned in https://github.com/alphapapa/ement.el/issues/38#issuecomment-1525586128, you can eval `(executable-find "curl.exe")` to see if Emacs can find the correct curl binary.  If it can't, you will need to ensure that the directory containing the real curl is in your path before the directory containing the fake curl.  

To do that you'll need to look at how you're running Emacs and set the path properly there.  And that's a question to be asked in a Windows forum (or web search).

**Comment by altomcat** [comment]
@kaibagley , I downloaded the lastest release for curl [here](https://curl.se/download.html). At the time, it was curl 8.0.1 (x86_64-w64-mingw32).

Then I usually  move executable binaries  to my home folder.
With _use-package_,  you can set `plz-curl-program` like this: 

``` elisp
(use-package ement
  :commands (ement)
  :init
  (when (eq system-type 'windows-nt)
    (setq plz-curl-program (concat user-windows-path "/my_path_to/curl.exe")))
  :config
...
)
```
If it doesn't work, you can try to add the directory that contains the curl executable to the beginning of your path.

**Comment by alphapapa** [comment]
@altomcat Thanks.  :)

**Comment by kaibagley** [comment]
@altomcat, thanks for the response! After setting the `plz-curl-program` variable, it still doesn't work however...

After running `(plz 'get "https://httpbin.org/user-agent")` I get a `nil` returned,
and after running `ement-connect`, i get `Ement: ‘plz’ request for .well-known URI did not return a ‘plz’ response`

@alphapapa, Thanks for clarifying, I think I'll have to look into the PATH variable thing, as adding it to the top of my PATH doesn't seem to change anything al all for whatever reason..

**Comment by alphapapa** [comment]
@kaibagley It works for me and at least hundreds of other users, so I don't know what the problem could be.  You also haven't said what versions of curl, `plz`, and Emacs that you're using.

**Comment by kaibagley** [comment]
Updated the first comment to include that information

**Comment by alphapapa** [comment]
@davidkidd Since your homeserver is returning a HTTP redirect for the well-known URL, you'll need to install `plz` from the master branch, which supports this: https://github.com/alphapapa/plz.el#06-pre  Or you could wait for v0.6 to be tagged, which will probably happen soon.

@kaibagley The same solution might work for you.  Please let me know if it does.

**Comment by davidkidd** [comment]
@alphapapa Thanks. I'm not sure how to install plz from the master branch. I tried putting it in my load path, but I think it just loads the plz that gets installed through quelpa. I'm new to emacs, so I'm probably doing something wrong. I'll just wait for 0.6 to be tagged.

**Comment by kaibagley** [comment]
Using the master branch `plz` doesn't change much for me, it still behaves the same as I've described above.

I'm sorry, I wish I could be a bit more helpful but I'm also quite new to Emacs.

I'll keep messing around with stuff and let you know if I can get it to work.

**Comment by alphapapa** [comment]
@davidkidd @kaibagley I'd recommend following the instructions in the readme to use `quelpa-use-package` to install from `master`.

Make sure that you restart Emacs after doing so to ensure that it loads the newer version.

**Comment by alphapapa** [comment]
@kaibagley Ok, well, I'm afraid that's as much help as I can offer.  Maybe some other Windows users can help you debug it.  Please let me know if you find a solution.

**Comment by kaibagley** [comment]
That's all good, I really appreciate your help @alphapapa. Thank you very much!

**Comment by mateialexandru** [comment]
@kaibagley @alphapapa  I believe the issue is coming from `plz-curl-default-args` using an unavailable option for Windows (flag `--compressed`)

@kaibagley  Use customize variable (C-h v) for `plz-curl-default-args` and remove the `--compressed` argument, and it should work. (it did work on my Windows 11 machine :) )

**Comment by alphapapa** [comment]
@mateialexandru Thanks for mentioning that.  It would be easy enough to add that flag only on non-Windows platforms.  But do you know if omitting that flag prevents the Windows "curl" from requesting compressed content?  IOW, could you get a dump of the outgoing request headers for comparison, please?

**Comment by mateialexandru** [comment]
@alphapapa Yes! 
```
(plz 'get "https://httpbin.org/get" :as #'json-read)
((args) (headers (Accept . "*/*") (Host . "httpbin.org") (User-Agent . "curl/8.0.1") (X-Amzn-Trace-Id . "Root=1-64b163aa-548567da21a97c0333abe7e6")) (origin . "76.147.235.33") (url . "https://httpbin.org/get"))
```

**Comment by mateialexandru** [comment]
Also, this is the curl that I see pre-installed on Win11:

<img width="833" alt="image" src="https://github.com/alphapapa/plz.el/assets/6072070/9937221f-2335-4e13-a1d0-d65389e568b5">

**Comment by alphapapa** [comment]
Hm, yeah, the `Accept-Encoding` header seems to be missing.  Here's what I get:
```
((args)
 (headers
  (Accept . "*/*")
  (Accept-Encoding . "deflate, gzip, br")
  (Host . "httpbin.org")
  (User-Agent . "curl/7.74.0"))
 (url . "https://httpbin.org/get"))
```
I wonder if that actually stops servers from sending, e.g. on-the-fly compressed content.

**Comment by kaibagley** [comment]
> @kaibagley @alphapapa I believe the issue is coming from `plz-curl-default-args` using an unavailable option for Windows (flag `--compressed`)
> 
> @kaibagley Use customize variable (C-h v) for `plz-curl-default-args` and remove the `--compressed` argument, and it should work. (it did work on my Windows 11 machine :) )

I can confirm this works for me. Thanks so much!

**Comment by mateialexandru** [comment]
@alphapapa Another option is to provide instructions / capability to download a different version of CURL for Windows, one that supports compression.

Or we could try a simple test request and check if --compression generates an error code or not. 🤷‍♂️

Thoughts?

**Comment by kaibagley** [comment]
I am no longer having this issue after a recent-ish update. Forgot to close this a few weeks ago!!! Thanks for the help!

**Comment by mateialexandru** [comment]
Thank you! Switched to WSL2 Emacs and not hitting this issue anymore. Might come back to native Windows and will share experience then.
