### ISSUE TITLE
"Cannot set file date" "d:/HOME/.emacs.d/straight/build/plz/NOTES.org"

### ISSUE THREAD

**Issue by AnabasisXu** [alphapapa/plz.el#45]
Emacs 29.2 on Window shows the following alert:

Debugger entered--Lisp error: (file-date-error "Cannot set file date" "d:/HOME/.emacs.d/straight/build/plz/NOTES.org")

And with this bug, I cannot use [org-web-tools](https://github.com/alphapapa/org-web-tools), which depends on plz.

**Comment by alphapapa** [comment]
Hello,

Thanks for the report.  Please provide the full backtrace.

**Comment by alphapapa** [comment]
Upon closer inspection, I see that this appears to be a bug in `straight` that's happening during the installation process in which it's trying to set the modification time of a symlink to a non-existent file.  That would be a bug in `straight`, not in `plz`.  If you install `plz` with `package-install` it will likely work fine.

**Comment by AnabasisXu** [comment]
Hi alphapapa, thank you for looking into this. 

I did use "use-package plz", but since I have `(setq straight-use-package-by-default t)` it uses straight anyway.

It there any workaround if I have to use straight? Set straight-use-package-by-default to nil will affect a lot of things..

Sorry I am new to emacs...

**Comment by AnabasisXu** [comment]
https://github.com/alphapapa/plz.el/blob/master/NOTES.org
The file that causes the straight problem is a link to the real file right? Is it better for it to be the real file instead of a link?

**Comment by alphapapa** [comment]
You do not need to use `straight` to install this package, or any of my packages, except for a few.  They are installable directly from inside Emacs with the `package-install` command as they are on GNU ELPA and MELPA.  See https://github.com/alphapapa/plz.el#installation

**Comment by AnabasisXu** [comment]
I eventually solved this issue by excluding the `NOTES.org` file with `straight`, as that file is empty anyway. I am getting too used to using `straight`, but change it would cause too many other changes...

`
(use-package plz
		:straight (plz
							 :type git
							 :host github
							 :repo "alphapapa/plz.el"
		:files (:defaults (:exclude "NOTES.org")))
)
`

Thanks anyway! 

I am a big fan of your packages, and words can hardly express my gratitude as they make my Emacs like so much better.

**Comment by alphapapa** [comment]
Straight is not without its own issues, as you have noticed.  There are alternatives that would work fine in this case, e.g.

`
(use-package plz
		:quelpa (plz
							 :type git
							 :host github
							 :repo "alphapapa/plz.el"))
`

Which I use to keep my own packages up-to-date.  As well, see Elpaca, by the current maintainer of Straight.  It is hard to recommend that anyone use Straight anymore.

> I am a big fan of your packages, and words can hardly express my gratitude as they make my Emacs like so much better.

Thanks for the kind words.  I'm glad to hear that they're useful to you.

**Comment by AnabasisXu** [comment]
Thank you for recommending `quelpa` and I will definitely check it out!
