### ISSUE TITLE
Copyright status of mascot

### ISSUE THREAD

**Issue by spwhitton** [alphapapa/plz.el#6]
Hello,

I'm packaging plz for Debian. May I ask about the copyright status of the mascot image? Did you make it yourself?

Thanks.

**Comment by alphapapa** [comment]
Hello,

All of the mascot images on my projects are based on public domain or CC-share-alike-licensed images.

**Comment by alphapapa** [comment]
I re-found the image here: https://pixabay.com/photos/pigeon-city-dove-bird-animal-5280994/  It says, "Free for commercial use
No attribution required"

**Comment by alphapapa** [comment]
But then, it's also found here: https://www.maxpixel.net/Pigeon-Feather-City-Bird-Plumage-Dove-Animal-5280994  Which says: "CC0 Public Domain"  And public domain is DFSG-compatible.

Anyway, as I said, it's just to show in the readme on GitHub.  It's not important.

**Comment by spwhitton** [comment]
Many thanks for looking into this.  Seems like it's best just to exclude the image from the Debian package, which I've now done.
