### ISSUE TITLE
How to call a function a single time when all requests in the queue are finished?

### ISSUE THREAD

**Issue by Dima-369** [alphapapa/plz.el#8]
Let's say I take this example from the README:

```emacs-lisp
(defvar my-queue (make-plz-queue :limit 2))

(plz-run
 (plz-queue my-queue
   'get "https://httpbin.org/get?foo=0"
   :then (lambda (body) (message "%s" body))))
```

Can I run a function once when all requests are handled? At first, I thought that `:finally` would do that, but I misread how it works.

Is there maybe some way to access `plz-queue-last-request`?

**Comment by alphapapa** [comment]
Hi,

That is not currently implemented, but it seems like a good idea.  I could add a `:then` slot to the queue, so you could do something like `(make-plz-queue :then (lambda (queue) ...))`.  What do you think?

**Comment by Dima-369** [comment]
>  I could add a :then slot to the queue, so you could do something like (make-plz-queue :then (lambda (queue) ...))

That sounds great! I like it.

**Comment by Dima-369** [comment]
@alphapapa Hey, I saw you recently added this functionality. Can this issue be closed?

**Comment by alphapapa** [comment]
Hi Dima,

As usual, I forgot that there was an associated issue to close.  :)  Thanks for reminding me.

Yes, I'll close it, but please try the new feature out and let me know if it works for you.  Thanks.

**Comment by Dima-369** [comment]
> but please try the new feature out and let me know if it works for you.

It does indeed work, but I first had to check your tests how to use it as the README did not include it, although the changelog did. Since `(plz)` also has `:finally`, it was a bit confusing. Maybe you could add it to the example in the README?

```emacs-lisp
(make-plz-queue
  :limit 1
  :finally (lambda ()
    (message "finally")))
```

**Comment by alphapapa** [comment]
Yes, I should add it to the readme.  Thanks.

**Comment by alphapapa** [comment]
I don't want to make a v0.5.5 release just to add one line to the readme, so I'll do that in a future release.
